language: python

python:
  - "2.7"

install:
  # installing libgit2
  - git clone -b master git://github.com/libgit2/libgit2.git
  - mkdir libgit2/build
  - cd libgit2/build
  - cmake ..
  - cmake --build .
  - sudo cmake --build . --target install
  - cd ../..

  # installing pygit2
  - export LIBGIT2="/usr/local"
  - export LDFLAGS="-Wl,-rpath='$LIBGIT2/lib',--enable-new-dtags $LDFLAGS"
  - pip install pygit2

  # installing mongodb
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv 7F0CEB10
  - echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' | sudo tee /etc/apt/sources.list.d/10gen.list
  - sudo apt-get update
  - sudo apt-get install -y mongodb-10gen

  - make setup

script:
    # finally run tests
    - make ci_test

after_success:
  - coveralls
